var Turbo={version:"1.5.5",$_SERVER:location.protocol+"//"+location.host,mouse:{x:0,y:0,offsetX:0,offsetY:0},browser:{browsers:["MSIE","Firefox","Chrome","webOS","Android","iPad","iPhone","Safari","Opera"],mobileOS:["webOS","Android","iPhone","iPad"],browser:false,version:false,mobile:undefined},onMouseMove:false,$nodes:{},activeModules:{carousel:{},accordion:{},tooltip:{}},$:function(a){return this.$nodes[a]?this.$nodes[a]:this.$nodes[a]=document.getElementById(a)},$$:function(a,b){var c=[],d=0,
f=0,e=[],g="#"+a.id+"."+b;if(this.$nodes[g])return this.$nodes[g];else{if(a.getElementsByClassName!==undefined){e=a.getElementsByClassName(b);for(d=0;d<e.length;d+=1)c.push(e[d])}else if(a.hasChildNodes())for(d=0;d<a.childNodes.length;d+=1)if(a.childNodes[d].className!==undefined){e=a.childNodes[d].className.split(" ");for(f=0;f<e.length;f+=1)e[f]===b&&c.push(a.childNodes[d])}return this.$nodes[g]=c}},attach:function(a,b){var c=Array.prototype.slice.call(arguments,2);return function(){if(arguments.length>
0)for(var d=0;d<arguments.length;d+=1)c.push(arguments[d]);a.apply(b,c)}},getPosition:function(a){var b=0,c=0;b=a.offsetLeft;for(c=a.offsetTop;a.offsetParent;){a=a.offsetParent;b+=a.offsetLeft;c+=a.offsetTop}return{left:b,top:c}},getWindowSize:function(){var a={height:[document.documentElement.scrollHeight,document.documentElement.offsetHeight,document.documentElement.clientHeight],width:[document.documentElement.scrollWidth,document.documentElement.offsetWidth,document.documentElement.clientWidth],
innerHeight:[window.innerHeight,document.documentElement.clientHeight,document.body.clientHeight],innerWidth:[window.innerWidth,document.documentElement.clientWidth,document.body.clientWidth],left:[window.pageXOffset,document.documentElement.scrollLeft,document.body.scrollLeft],top:[window.pageYOffset,document.documentElement.scrollTop,document.body.scrollTop]},b={},c,d,f;for(c in a)if(a.hasOwnProperty(c)){for(d=f=0;d<a[c].length;d+=1)if(a[c][d]>f)f=a[c][d];b[c]=f}return b},getBrowser:function(){if(!this.browser.browser){var a,
b;for(a=0;a<this.browser.browsers.length;a+=1)if(navigator.userAgent.indexOf(this.browser.browsers[a])!==-1){this.browser.browser=this.browser.browsers[a];break}if(!this.browser.browser)this.browser.browser="Unknown Browser";b=this.browser.browser==="Safari"?"Version":this.browser.browser;a=navigator.userAgent.indexOf(b);if(a!==-1){this.browser.version="";for(a=a+b.length+1;a<=navigator.userAgent.length;a+=1){if(navigator.userAgent.substring(a,a+1)===" ")break;this.browser.version=this.browser.version+
""+navigator.userAgent.substring(a,a+1)}}else this.browser.version="Unknown Version"}return{browser:this.browser.browser,version:this.browser.version}},isMobileBrowser:function(){if(this.browser.mobile!==undefined)return this.browser.mobile;else{for(var a=0;a<this.browser.mobileOS.length;a+=1)if(Turbo.getBrowser().browser===this.browser.mobileOS[a])return this.browser.mobile=true;return this.browser.mobile=false}},defaults:function(a,b){a=a||{};for(var c in b)if(b.hasOwnProperty(c))a[c]=a[c]===undefined?
b[c]:a[c];return a},hasPositionFixed:function(){return Turbo.isMobileBrowser()||Turbo.getBrowser().browser==="MSIE"&&Turbo.getBrowser().version==="6.0;"?false:true}};Turbo.getMouseCoordinates=function(a){if(Turbo.getBrowser().browser==="MSIE"){Turbo.mouse.x=a.clientX+document.body.scrollLeft;Turbo.mouse.y=a.clientY+document.body.scrollTop}else{Turbo.mouse.x=a.pageX;Turbo.mouse.y=a.pageY}if(Turbo.mouse.x<0)Turbo.mouse.x=0;if(Turbo.mouse.y<0)Turbo.mouse.y=0;Turbo.onMouseMove&&Turbo.onMouseMove();return Turbo.mouse};
if(Turbo.getBrowser().browser==="MSIE"){document.attachEvent("onclick",Turbo.getMouseCoordinates);document.attachEvent("onmousemove",Turbo.getMouseCoordinates)}else{document.addEventListener("click",Turbo.getMouseCoordinates,false);document.addEventListener("mousemove",Turbo.getMouseCoordinates,false)}Turbo.Effects=function(a,b,c,d){Turbo.Animation.start(a,b,c,d)};
Turbo.Animation={timer:false,elementQueue:[],emile:{properties:["backgroundColor","borderBottomColor","borderBottomWidth","borderLeftColor","borderLeftWidth","borderRightColor","borderRightWidth","borderSpacing","borderTopColor","borderTopWidth","bottom","color","fontSize","fontWeight","height","left","letterSpacing","lineHeight","marginBottom","marginLeft","marginRight","marginTop","maxHeight","maxWidth","minHeight","minWidth","opacity","outlineColor","outlineOffset","outlineWidth","paddingBottom",
"paddingLeft","paddingRight","paddingTop","right","textIndent","top","width","wordSpacing","zIndex"],parseEl:false,interpolate:function(a,b,c){return(a+(b-a)*c).toFixed(3)},parse:function(a){var b=parseFloat(a);a=a.replace(/^[\-\d\.]+/,"");return{value:b,func:this.interpolate,suffix:a}},normalize:function(a){var b={},c=this.properties.length;this.parseEl.innerHTML='<div style="'+a+'"></div>';for(a=this.parseEl.childNodes[0].style;c>=0;){if(a[this.properties[c]])b[this.properties[c]]=this.parse(a[this.properties[c]]);
c-=1}return b}},start:function(a,b,c,d){a=typeof a==="string"?Turbo.$(a):a;c=Turbo.defaults(c,{duration:500,easing:function(i){return-Math.cos(i*Math.PI)/2+0.5}});if(!this.emile.parseEl)this.emile.parseEl=document.createElement("div");b=this.emile.normalize(b);var f=a.currentStyle?a.currentStyle:getComputedStyle(a,null),e,g={},h=(new Date).getTime(),j=h+c.duration;for(e in b)if(b.hasOwnProperty(e))g[e]=this.emile.parse(f[e]);this.elementQueue.push({id:this.elementQueue.length,element:a,opts:c,start:h,
end:j,target:b,current:g,callback:d});if(!this.timer)this.timer=setInterval(Turbo.attach(this.run,this),10)},stop:function(){clearInterval(this.timer);this.timer=false;this.elementQueue=[]},run:function(){var a=(new Date).getTime(),b,c,d,f=0,e;for(d=0;d<this.elementQueue.length;d+=1){e=this.elementQueue[d];if(e===null){f+=1;f===this.elementQueue.length&&this.stop()}else{b=a>e.end?1:(a-e.start)/e.opts.duration;for(c in e.target)if(e.target.hasOwnProperty(c))e.element.style[c]=e.target[c].func(e.current[c].value,
e.target[c].value,e.opts.easing(b))+e.target[c].suffix;if(a>e.end){e.callback&&e.callback();this.elementQueue[d]=null}}}}};
Turbo.Ajax=function(a,b,c){this.http=false;this.url=a.indexOf("http://")!==-1?a:Turbo.$_SERVER+"/"+a;if(b){a=false;var d=[];for(a in b)b.hasOwnProperty(a)&&d.push(a+"="+b[a]);this.parameters=d.join("&")}try{this.http=new XMLHttpRequest}catch(f){try{this.http=new ActiveXObject("Msxml2.XMLHTTP")}catch(e){try{this.http=new ActiveXObject("Microsoft.XMLHTTP")}catch(g){alert("We apologize, your browser does not support Ajax");return false}}}this.handleRequest=function(){switch(typeof c){case "string":Turbo.$(c).innerHTML=
this.http.responseText;break;case "function":return c(this.http);default:return false}};this.post=function(){this.http.open("POST",this.url,true);this.http.setRequestHeader("Content-type","application/x-www-form-urlencoded");this.http.setRequestHeader("Content-length",this.parameters.length);this.http.setRequestHeader("Connection","close");this.http.send(this.parameters);this.http.onreadystatechange=Turbo.attach(function(){if(this.http.readyState===4)return this.handleRequest()},this)};this.get=function(){this.url=
this.parameters?this.url+"?"+this.parameters:this.url;this.http.open("GET",this.url,true);this.http.send(null);this.http.onreadystatechange=Turbo.attach(function(){if(this.http.readyState===4)return this.handleRequest()},this)}};
Turbo.ActivityIndicator={config:{imageMouse:"images/ajaxloader.gif",imageScrim:"images/ajaxloader2.gif"},follow:function(){this.ajaxLoader.style.top=Turbo.mouse.y+10+"px";this.ajaxLoader.style.left=Turbo.mouse.x+10+"px"},show:function(a){if(!this.ajaxLoader){this.ajaxLoader=document.createElement("img");if(a){this.scrim=Turbo.Scrim.show();this.scrim.className="trScrim trActivity";this.ajaxLoader.src=this.config.imageScrim;this.ajaxLoader.className="trActivityIndicatorScrim";if(!Turbo.hasPositionFixed()){var b=
Turbo.getWindowSize();this.ajaxLoader.style.position="absolute";this.ajaxLoader.style.top=Math.floor(b.innerHeight/2)+b.top+"px";this.ajaxLoader.style.left=Math.floor(b.innerWidth/2)+b.left+"px"}}else{this.ajaxLoader.src=this.config.imageMouse;this.ajaxLoader.className="trActivityIndicator"}document.body.appendChild(this.ajaxLoader);this.ajaxLoader.style.display="block";if(!a){this.follow();Turbo.onMouseMove=Turbo.attach(this.follow,this)}}},hide:function(){if(this.ajaxLoader){this.ajaxLoader.parentNode.removeChild(this.ajaxLoader);
this.ajaxLoader=null;if(this.scrim)this.scrim=Turbo.Scrim.hide(this.scrim)}Turbo.onMouseMove=false}};Turbo.Scrim={show:function(){var a=document.createElement("div"),b;if(!Turbo.hasPositionFixed()){b=Turbo.getWindowSize();a.style.width=b.width+"px";a.style.height=b.height+"px"}a.className="trScrim";document.body.appendChild(a);return a},hide:function(a){document.body.removeChild(a);return null}};
Turbo.Notification=function(a,b){b=Turbo.defaults(b,{id:(new Date).getTime(),timeout:15E3,type:"neutral"});b.id="trN"+b.id;this.interval=false;this.father=function(){if(Turbo.$("trNotificationChain"))return Turbo.$("trNotificationChain");else{this.chain=document.createElement("div");this.chain.id="trNotificationChain";document.body.appendChild(this.chain);return this.chain}};this.kill=function(){if(this.note){this.note.onmouseup=function(){};Turbo.Effects(this.note,"top: -"+this.note.offsetHeight+
"px",{duration:200},Turbo.attach(function(){this.chain.removeChild(this.note);this.note=null},this))}};this.child=function(){if(Turbo.$(b.id)){this.note=Turbo.$(b.id);if(Turbo.$(b.id+"ct"))this.counter=Turbo.$(b.id+"ct");else{this.counter=document.createElement("span");this.counter.className="trCount";this.counter.id=b.id+"ct";this.counter.innerHTML="1";this.note.appendChild(this.counter)}this.counter.innerHTML=parseInt(this.counter.innerHTML,10)+1}else{this.chain=this.father();if(!Turbo.hasPositionFixed()){var c=
Turbo.getWindowSize();this.chain.style.position="absolute";this.chain.style.top=c.top+"px"}this.note=document.createElement("div");this.note.id=b.id;this.chain.appendChild(this.note);this.note.className="trNotification "+b.type;this.note.style.display="none";this.note.innerHTML=a;this.note.onmouseup=Turbo.attach(this.kill,this);this.note.style.display="block";this.note.style.top="-"+this.note.offsetHeight+"px";Turbo.Effects(this.note,"top: 0px",{duration:200});window.setTimeout(Turbo.attach(this.kill,
this),b.timeout)}};this.child()};
Turbo.Lightbox={dimensions:{width:false,height:false,left:0,top:0},url:false,isActive:function(){return this.wrapper?true:false},close:function(){this.lightBox.style.display="none";if(this.wrapper){this.wrapper.parentNode.removeChild(this.wrapper);this.wrapper=null}if(this.scrim)this.scrim=Turbo.Scrim.hide(this.scrim)},show:function(a,b){if(a===this.url&&this.isActive())return false;else this.url=a;this.wrapper&&this.close();Turbo.ActivityIndicator.show();this.scrim=Turbo.Scrim.show();this.scrim.style.display=
"none";this.wrapper=document.createElement("div");this.wrapper.className="trLightbox-wrapper";this.lightBox=document.createElement("div");this.lightBox.className="trLightbox";this.closeBtn=document.createElement("a");this.closeBtn.className="close";this.closeBtn.innerHTML="X";this.closeBtn.onmouseup=Turbo.attach(this.close,this);this.scrim.onmouseup=Turbo.attach(this.close,this);this.wrapper.appendChild(this.lightBox);this.wrapper.appendChild(this.closeBtn);document.body.appendChild(this.wrapper);
if(a.substr(0,1)==="#"){this.lightBox.innerHTML=Turbo.$(a.substr(1,a.length)).innerHTML;this.load(b)}else(new Turbo.Ajax(a,false,Turbo.attach(function(c){this.lightBox.innerHTML=c.responseText;this.load(b)},this))).get()},load:function(a){var b=document.documentElement.clientWidth/2,c=document.documentElement.clientHeight/2;this.dimensions={width:this.lightBox.offsetWidth<b+this.lightBox.offsetWidth?this.lightBox.offsetWidth:b,height:this.lightBox.offsetHeight<c+this.lightBox.offsetHeight?this.lightBox.offsetHeight:
c};this.wrapper.style.width=this.dimensions.width+"px";this.wrapper.style.height=this.dimensions.height+"px";this.dimensions.left=b-(this.dimensions.width/2+(this.wrapper.offsetWidth-this.dimensions.width)/2);this.dimensions.top=c-(this.dimensions.height/2+(this.wrapper.offsetHeight-this.dimensions.height)/2);if(!Turbo.hasPositionFixed()){b=Turbo.getWindowSize();this.wrapper.style.position="absolute";this.dimensions.top+=b.top;this.dimensions.left+=b.left}this.dimensions.left=this.dimensions.left>
0?this.dimensions.left:0;this.dimensions.top=this.dimensions.top>0?this.dimensions.top:0;this.wrapper.style.display="none";this.wrapper.style.left=this.dimensions.left+"px";this.wrapper.style.top=this.dimensions.top+"px";this.lightBox.style.visibility="hidden";Turbo.ActivityIndicator.hide();this.scrim.style.opacity="0";this.scrim.style.display="block";Turbo.Effects(this.scrim,"opacity: 0.85",null,Turbo.attach(function(){this.wrapper.style.display="block"},this));this.lightBox.style.visibility="visible";
a&&a()}};
Turbo.Tooltip=function(a,b,c){this.element=typeof a==="string"?Turbo.$(a):a;if(Turbo.activeModules.tooltip[a.id])return false;else Turbo.activeModules.tooltip[a.id]=true;this.url=b;this.dimensions={width:0,height:0,left:0,top:0};this.original={documentWidth:0,documentHeight:0,elementLeft:0,elementTop:0,elementWidth:0,elementHeight:0};c=Turbo.defaults(c,{showDelay:250,hideDelay:10,followMouse:false,allowTooltipHover:false});this.hideMe=true;this.create=function(){this.tooltip=document.createElement("div");this.tooltip.className=
"trTooltip";this.stem=document.createElement("div");this.stem.className="trTooltip-stem";document.body.appendChild(this.tooltip);this.tooltip.appendChild(this.stem);if(this.url.substr(0,1)==="#"){var d=document.createElement("div");d.innerHTML=Turbo.$(this.url.substr(1,this.url.length)).innerHTML;this.tooltip.appendChild(d);this.load()}else{Turbo.ActivityIndicator.show();(new Turbo.Ajax(this.url,false,Turbo.attach(function(f){Turbo.ActivityIndicator.hide();var e=document.createElement("div");e.innerHTML=
f.responseText;this.tooltip.appendChild(e);this.load()},this))).get()}};this.load=function(){this.tooltip.style.display="block";this.tooltip.style.left="-10000px";if(this.element.offsetParent){this.elementOffset=Turbo.getPosition(this.element);this.dimensions={left:c.followMouse?Turbo.mouse.x:this.elementOffset.left+this.element.offsetWidth,top:c.followMouse?Turbo.mouse.y:this.elementOffset.top+this.element.offsetHeight/2-this.tooltip.offsetHeight/2}}else this.dimensions={left:c.followMouse?Turbo.mouse.x:
this.element.offsetLeft+this.element.offsetWidth,top:c.followMouse?Turbo.mouse.y:this.element.offsetTop+this.element.offsetHeight/2-this.tooltip.offsetHeight/2};if(this.dimensions.left>document.documentElement.clientWidth-this.tooltip.offsetWidth)if(this.element.offsetLeft-this.tooltip.offsetWidth<0)this.dimensions.left=Turbo.mouse.x+25;else{this.dimensions.left=this.dimensions.left-(this.element.offsetWidth+this.tooltip.offsetWidth)-25;this.tooltip.className="trTooltip right"}else this.tooltip.className=
"trTooltip";this.original={documentWidth:document.documentElement.clientWidth,documentHeight:document.documentElement.clientHeight,elementWidth:this.element.offsetWidth,elementHeight:this.element.offsetHeight,elementLeft:this.element.offsetLeft,elementTop:this.element.offsetTop};this.tooltip.style.display="none";this.tooltip.style.left=this.dimensions.left+"px";this.tooltip.style.top=this.dimensions.top+"px";this.show()};this.show=function(){if(this.showMe)if(this.tooltip){if(document.documentElement.clientWidth!==
this.original.documentWidth||document.documentElement.clientHeight!==this.original.documentHeight||this.element.offsetWidth!==this.original.elementWidth||this.element.offsetHeight!==this.original.elementHeight||this.element.offsetLeft!==this.original.elementLeft||this.element.offsetTop!==this.original.elementTop)this.load();this.tooltip.style.display="block"}else this.create()};this.hide=function(){if(this.tooltip&&this.hideMe)this.tooltip.style.display="none"};this.element.onmouseover=Turbo.attach(function(){this.showMe=
true;window.setTimeout(Turbo.attach(this.show,this),c.showDelay)},this);this.element.onmouseout=Turbo.attach(function(){this.showMe=false;window.setTimeout(Turbo.attach(this.hide,this),c.hideDelay)},this)};
Turbo.Accordion=function(a,b,c,d){a=typeof a==="string"?Turbo.$(a):a;if(Turbo.activeModules.accordion[a.id])return false;else Turbo.activeModules.accordion[a.id]=true;this.toggle=typeof b==="string"?Turbo.$$(a,b):b;this.content=typeof c==="string"?Turbo.$$(a,c):c;this.offset=[];this.activeAccordion=false;d=Turbo.defaults(d,{style:"vertical"});this.collapseAccordion=function(f){Turbo.Effects(this.content[f],"height: 0px")};this.selectAccordion=function(f){this.activeAccordion&&this.collapseAccordion(this.activeAccordion);
if(this.activeAccordion!==f){Turbo.Effects(this.content[f],"height: "+this.offset[f].height+"px");this.activeAccordion=f}else this.activeAccordion=false};for(a=0;a<this.toggle.length;a+=1){this.toggle[a].style.cursor="pointer";this.toggle[a].onclick=Turbo.attach(this.selectAccordion,this,a);this.offset[a]={width:this.content[a].offsetWidth,height:this.content[a].offsetHeight};this.content[a].style.height="0px";this.content[a].style.overflow="hidden"}};
Turbo.Carousel=function(a,b,c){a=typeof a==="string"?Turbo.$(a):a;if(Turbo.activeModules.carousel[a.id])return false;else Turbo.activeModules.carousel[a.id]=true;b=typeof b==="string"?Turbo.$$(a,b):b;c=Turbo.defaults(c,{style:"horizontal",overflow:false,slideshow:false,interval:3E3,scroller:false,page:1});this.current=0;this.scrolling=false;this.width=a.offsetWidth;this.height=a.offsetHeight;this.getLastPage=function(){return b.length};this.getPage=function(){return this.page};var d=document.createElement("div");
d.style.position="absolute";d.style.top="0px";d.style.left="0px";if(c.style==="vertical")d.style.height=b.length*this.height+"px";else d.style.width=b.length*this.width+"px";this.contentNext=function(){d.appendChild(b[0]);b.push(b.shift())};this.contentPrev=function(){d.insertBefore(b[this.getLastPage()-1],b[this.current]);b.unshift(b[this.getLastPage()-1]);b.splice(this.getLastPage()-1,1)};this.afterScroll=function(){this.scrolling=false;if(c.overflow){if(this.current>1)this.contentNext();else this.current<
1&&this.contentPrev();this.current=1;if(c.style==="vertical")d.style.top="-"+this.height+"px";else d.style.left="-"+this.width+"px"}if(c.scroller)this.next();else c.slideshow&&window.setTimeout(Turbo.attach(this.next,this),c.interval)};this.moveCarousel=function(){var f=c.scroller?25E3:500,e=c.scroller?function(h){return h}:undefined,g=c.style==="horizontal"?"left: -"+this.current*this.width+"px":"top: -"+this.current*this.height+"px";this.scrolling=true;Turbo.Effects(d,g,{duration:f,easing:e},Turbo.attach(this.afterScroll,
this))};this.next=function(){if(this.current<this.getLastPage()-1&&!this.scrolling){this.page+=1;if(this.getPage()>this.getLastPage())this.page=1;this.current+=1;this.moveCarousel()}};this.previous=function(){if(this.current>0&&!this.scrolling){this.page-=1;if(this.getPage()<1)this.page=this.getLastPage();this.current-=1;this.moveCarousel()}};for(this.current=0;this.current<b.length;this.current+=1){if(c.style==="vertical")b[0].style.height=this.height+"px";else{b[0].style.width=this.width+"px";b[0].style.cssFloat=
"left"}this.contentNext()}this.current=0;if(c.overflow){if(c.style==="vertical")d.style.top="-"+this.height+"px";else d.style.left="-"+this.width+"px";this.contentPrev();this.current=1}a.style.overflow="hidden";a.style.position="relative";a.appendChild(d);this.page=1;if(c.scroller)this.next();else c.slideshow&&window.setTimeout(Turbo.attach(this.next,this),c.interval)};
